default_language_version:
  python: python3
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
    - id: ruff-check  # isort
      args: ["--select", "I", "--fix"]
    - id: ruff-format