name: release-action

# Run on pull requests and on the master branch itself.
on:
  push:
    branches:
      - master
      - basten_pluginRelease
    tags:
      - "*"
  pull_request:


jobs:
  build_upload:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the code.
      - uses: actions/checkout@v2

      - name: build
        run: |
          docker build . -t schema
          docker run -w /app/ -v "$(pwd):/app" -it schema make test
          docker run -w /app/ -v "$(pwd):/app" -it schema make zip

      - name: Publish package
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          make zip
          bash upload-artifact.sh
        env:
          ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}

